INICIO:
    LDI R20, 0XFF
    OUT DDRD, R20 ;PUERTO D COMO ENTRADA
    OUT DDRC, R20 ; PUERTO C COMO ENTRADA
    LDI R20, 0X00
    OUT DDRB, R20; PUERTO B COMO ENTRADA
	
	LDI R16,0XC0
	OUT PORTD,R16

PRE_LEDS:;SUBRUTINA PRINCIPAL
	OUT PORTC, R24;MUESTRA EL VALOR DE R24, ESTO SE HACE PARA QUE MANTENGA EL VALOR MOSTRADO EN LOS LEDS
	IN R20, PINB; CARGA LO QUE TIENE, ENTRA DEL PUERTO B AL REGISTRO R20

;COMPARACIONES PARA SABER SI DOS O MAS PULSADORES FUERON PULSADOS
	LDI R17, 0X03;CARGUE EL VALOR DE 03 EN EL REGISTRO R17
	CPSE R20, R17;COMPARE R20 CON R17
	RJMP COMPARA1;SI NO ES IGUAL LA COMPARACION SALTE A COMPARAR 1
	CALL CICLO_LED; SI ES IGUAL LA COMPARACION SALTE A CICLO LED

	COMPARA1:
	LDI R17, 0X05;CARGUE EL VALOR DE 05 EN EL REGISTRO R17
	CPSE R20, R17;COMPARE R20 CON R17
	RJMP COMPARA2;SI NO ES IGUAL LA COMPARACION SALTE A COMPARA 2
	CALL CICLO_LED;SI ES IGUAL LA COMPARACION SALTE A CICLO LED
	COMPARA2:
	LDI R17, 0X06
	CPSE R20, R17
	RJMP COMPARA3
	CALL CICLO_LED
	COMPARA3:
	LDI R17, 0X07
	CPSE R20, R17
	RJMP COMPARA4
	CALL CICLO_LED
	COMPARA4:
	LDI R17, 0X09
	CPSE R20, R17
	RJMP COMPARA5
	CALL CICLO_LED
	COMPARA5:
	LDI R17, 0X0A
	CPSE R20, R17
	RJMP COMPARA6
	CALL CICLO_LED
	COMPARA6:
	LDI R17, 0X0B
	CPSE R20, R17
	RJMP COMPARA7
	CALL CICLO_LED
	COMPARA7:
	LDI R17, 0X0C
	CPSE R20, R17
	RJMP COMPARA8
	CALL CICLO_LED
	COMPARA8:
	LDI R17, 0X0D
	CPSE R20, R17
	RJMP COMPARA9
	CALL CICLO_LED
	COMPARA9:
	LDI R17, 0X0E
	CPSE R20, R17
	RJMP COMPARA10
	CALL CICLO_LED
	COMPARA10:
	LDI R17, 0X0F
	CPSE R20, R17
	RJMP COMPARA11
	CALL TODOSPRENDIDOS ;TODOS LOS LEDS PRENDIDAS
	COMPARA11:
    CALL ELEGIR
    RJMP PRE_LEDS

PULSADOR1:;SUBRUTINA PARA DETECTAR LOS PULSOS EN EL BIT 0 DEL PUERTO B
	LDI R16, 0XF9;CARGA R16 CON F9
    OUT PORTD, R16; MUESTRA EL VALOR DE R16 EN EL PUERTO D(DISPLAY)
    CALL RETARDO; LLAMA A RETARDO
    OUT PORTC,R18; SACA EL VALOR DEL REGISTRO R18 POR EL PUERTO C(0)
    LDI R25, 0X01;CARGA EL REGSTRO R25 CON 0X01
    OR R24,R25; HACE UNA OR ENTRE R24 Y R25
	CALL CONTADOR; LLAMA A CONTADOR (SUBRUTINA PARA PRENDER Y APAGAR LOS LEDS)
    CALL ELEGIR; LLAMA A SUBRUTINA ELEGIR(DETECTA PULSOS EN EL PUERTO B)
    RJMP PULSADOR1
PULSADOR2:
    LDI R20, 0XA4    ; CONFIGURAR NUMERO A VER
    OUT PORTD, R20
    CALL RETARDO
    OUT PORTC,R18
    LDI R25, 0X02    ;ENCENDER LED
    OR R24,R25
	CALL CONTADOR
	CALL ELEGIR
    RJMP PULSADOR2
PULSADOR3:
    LDI R20, 0XB0    ; CONFIGURAR NUMERO A VER
    OUT PORTD, R20
    CALL RETARDO
    OUT PORTC,R18
    LDI R25, 0X04    ;ENCENDER LED
    OR R24,R25
	CALL CONTADOR
    CALL ELEGIR
    RJMP PULSADOR3
PULSADOR4:
    LDI R20, 0X99    ; CONFIGURAR NUMERO A VER
    OUT PORTD, R20
    CALL RETARDO
    OUT PORTC,R18
    LDI R25, 0X08    ;ENCENDER LED
    OR R24,R25
	CALL CONTADOR
    CALL ELEGIR
    RJMP PULSADOR4

CONTADOR:; ETIQUETA PARA ENVIAR A AL FUNCIONAMIENTO DEL DISPLAY
	LDI R26, 0X03;CARGA R26 CON 0X03    0011 [PUERTO PB0 PB1]
	IN R20,PINB; CARGA R20 CON LA ENTRADA POR EL PUERTO B
	CP R20,R26;COMPARA R20 Y R66
	BREQ CICLO_LED; SI LA COMPARACION ES VERDAD SALTA A LA ETIQUETA PARA EL CONTEO

	LDI R26, 0X05;SI LA COMPARACION NO ES IGUAL CARGA R26 CON 0X05   0101 [PUERTO PB0 PB2]
	IN R20,PINB; CARGA R20 CON LA ENTRADA POR EL PUERTO B
	CP R20,R26;COMPARA R20 Y R26
	BREQ CICLO_LED; SI LA COMPARACION ES VERDAD SALTA A LA ETIQUETA PARA EL CONTEO
	
	LDI R26, 0X06   ;0110 [PUERTO PB1 PB2]
	IN R20,PINB
	CP R20,R26
	BREQ CICLO_LED
	
	LDI R26, 0X07	;0111 [PUERTO PB0 PB1 PB2]
	IN R20,PINB
	CP R20,R26
	BREQ CICLO_LED
	
	LDI R26, 0X09	;1001 [PUERTO PB0 PB3]
	IN R20,PINB
	CP R20,R26
	BREQ CICLO_LED
	
	LDI R26, 0X0A	;1010 [PUERTO PB1 PB3]
	IN R20,PINB
	CP R20,R26
	BREQ CICLO_LED
	
	LDI R26, 0X0B	;1011 [PUERTO PB0 PB1 PB3]
	IN R20,PINB
	CP R20,R26
	BREQ CICLO_LED
	
	LDI R26, 0X0C	;1100 [PUERTO PB2 PB3]
	IN R20,PINB
	CP R20,R26
	BREQ CICLO_LED
	
	LDI R26, 0X0D	;1101 [PUERTO PB0 PB2 PB3]
	IN R20,PINB
	CP R20,R26
	BREQ CICLO_LED
	
	LDI R26, 0X0E	;1110 [PUERTO PB1 PB2 PB3]
	IN R20,PINB
	CP R20,R26
	BREQ CICLO_LED

	;NO HAY UN "LDI R26, 0X0F" YA QUE ESTA SE DIRIJE A LA ETIQUETA TODOS PRENDIDOS

    CALL RETARDO
    OUT PORTC,R24
	RET

CICLO_LED:;
	LDI R24,0X0F ; PRENDE TODOS LOS LEDS
	OUT PORTC,R24; LO MUESTRA
	CALL RETARDOREINICIO; LLAMA RETARDO (1s)
	CLR R22;LIMPIA R22
	CLR R24;LIMPIA R24
    RJMP INICIO

ELEGIR:; ETIQUETA PARA DETECTAR PULSOS EN PUERTO B
	IN R20, PINB; R20 TOMA EL VALOR DEL PUERTO B
    BST R20, 0; DETECTA SI HAY UN PULSO EN EL BIT 0 DEL PUERTO B
    BRTS PULSADOR11; SI HUBO UN PULSO EN EL BIT 0 LO ENVIA A LA ETIQUETA PULSADOR11
    BST R20, 1; DETECTA SI HAY UN PULSO EN EL BIT 1 DEL PUERTO B
    BRTS PULSADOR22; SI HUBO UN PULSO EN EL BIT 1 LO ENVIA A LA ETIQUETA PULSADOR22
    BST R20, 2; DETECTA SI HAY UN PULSO EN EL BIT 2 DEL PUERTO B
    BRTS PULSADOR33; SI HUBO UN PULSO EN EL BIT 2 LO ENVIA A LA ETIQUETA PULSADOR33
    BST R20, 3; DETECTA SI HAY UN PULSO EN EL BIT 3 DEL PUERTO B
    BRTS PULSADOR44; SI HUBO UN PULSO EN EL BIT 3 LO ENVIA A LA ETIQUETA PULSADOR44
	BST R20, 4; DETECTA SI HAY UN PULSO EN EL BIT 4 DEL PUERTO B
    BRTS PULSADOR5; SI HUBO UN PULSO EN EL BIT 4 LO ENVIA A LA ETIQUETA PULSADOR5
	RET; VUELVE A DONDE LA LLAMARON

PULSADOR11:
    CALL PULSADOR1
PULSADOR22:
	CALL PULSADOR2
PULSADOR33:
	CALL PULSADOR3
PULSADOR44:
	CALL PULSADOR4
PULSADOR5:;ETIQUETA CREADA PARA CUANDO SE DETECTAN LOS 3 PULSOS PARA EL REINICIO
	CALL LED_ON_OFF;LLAMA A LED_ON_OFF
	CALL RETARDOREI;LLAMA A RETARDO DE REINICIO (500ms)
	CALL LED_ON_OFF;LLAMA A LED_ON_OFF
	LDI R23, 0X03; ASIGNA R23 COMO 0X03
	INC R22 ;INCREMENTA EL VALOR DE R22 CON 1
	CPSE R23,R22;COMPARA R23 CON R22
	CALL PRE_LEDS;LLAMA A ETIQUETA DE COMPARACION
	CALL REINICIO;LLAMA A REINICIO

LED_ON_OFF:; ETIQUETA PRENDIDO Y APAGADO DE LEDS
	OUT PORTC,R24; MUESTRE EL VALOR DE R24(ACUMULADO) EN EL PUERTO C
	CALL RETARDO; LLAMA RETARDO (500ms)
	LDI R23,0X00;CARGUE R23 CON 00
	OUT PORTC,R23; SAQUELO POR E PUERTO C
	CALL RETARDO;LLAME A RETARDO
	RET; REGRESE A DONDE FUE LLAMADO

REINICIO:; REINICIO CONTEO DISPLAY DE 3 A 9
	LDI R21,0XB0 ;3
    OUT PORTD,R21
    CALL RETARDO
	CALL LED_ON_OFF

    LDI R21,0X99 ;4
    OUT PORTD,R21
    CALL RETARDO
	CALL LED_ON_OFF

    LDI R21,0X92 ;5
    OUT PORTD,R21
    CALL RETARDO
	CALL LED_ON_OFF

    LDI R21,0X82 ;6
    OUT PORTD,R21
    CALL RETARDO
	CALL LED_ON_OFF

    LDI R21,0XF8 ;7
    OUT PORTD,R21
    CALL RETARDO
	CALL LED_ON_OFF

	LDI R21,0X80 ;8
    OUT PORTD,R21  
    CALL RETARDO
	CALL LED_ON_OFF
	
	LDI R21,0X90 ;9
    OUT PORTD,R21
    CALL RETARDO
	CALL LED_ON_OFF

	LDI R21,0XC0 ;0 -> EL DISPLAY DESPUES DEL CONTEO QUEDA EN CERO
    OUT PORTD,R21
    CALL RETARDO
	
	;--------------------------------------REINICIO LEDS----------------------------------------------
	LDI R29, 0X00;CARGA R29 CON 00
	OUT PORTC, R19;MUESTRA EL VALOR DE R29 EN EL PUERTO C
	CLR R22;LIMPIA R22
	CLR R24;LIMPIA R24
	RJMP PRE_LEDS;SALTA A COMPARAR

RETARDOREI:
    ldi  r18, 65
    ldi  r19, 240
    ldi  r20, 52
L2: dec  r20
    brne L2
    dec  r19
    brne L2
    dec  r18
    brne L2
	RET

TODOSPRENDIDOS: 
    LDI R30, 0X08
	OUT PORTD, R30
	CALL RETARDO
	LDI R22, 0X0F
	OUT PORTC, R22
	CALL RETARDO
	RJMP PRE_LEDS

RETARDO: ;RETARDO LEDS 500MS
    ldi  r18, 41
    ldi  r19, 150
    ldi  r20, 128
L1: dec  r20
    brne L1
    dec  r19
    brne L1
    dec  r18
    brne L1
    RET

RETARDOREINICIO: ;RETARDO 1SEG
    ldi  r18, 82
    ldi  r19, 43
    ldi  r20, 0
L3: dec  r20
    brne L3
    dec  r19
    brne L3
    dec  r18
    brne L3
    lpm
    nop
	ret

FIN:
    RJMP FIN
